import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import{mkdirSync}from'node:fs';
mkdirSync('test-results',{recursive:true});const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173');await page.getByRole('button',{name:'افتح الدعوة'}).waitFor();await page.screenshot({path:'test-results/opening-mobile.png'});await page.getByRole('button',{name:'افتح الدعوة'}).click();await page.waitForTimeout(400);
assert.equal(await page.locator('audio').first().evaluate(a=>a.paused),false,'opening starts audio');await page.locator('.floating-music').click();assert.equal(await page.locator('audio').first().evaluate(a=>a.paused),true);await page.locator('.floating-music').click();assert.equal(await page.locator('audio').first().evaluate(a=>a.paused),false);
for(const width of [375,390,393,402,430,1440]){await page.setViewportSize({width,height:900});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`no overflow at ${width}`)}
await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/hero-mobile.png'});
const rsvp=page.locator('#rsvp');await rsvp.getByLabel('الاسم الكامل').fill('سارة اختبار');await rsvp.getByLabel('رقم الهاتف').fill('+966 555123456');await rsvp.getByLabel('عدد الأشخاص').selectOption('3');await rsvp.getByRole('button',{name:'تأكيد الحضور'}).click();await rsvp.getByText('تم تسجيل ردك بنجاح.').waitFor();
const book=page.locator('.guestbook');await book.getByLabel('الاسم',{exact:true}).fill('رسالة اختبار');await book.getByLabel('الرسالة',{exact:true}).fill('ألف مبارك للعروسين 🤍');await book.getByRole('button',{name:'إرسال الرسالة'}).click();await book.locator('article').getByText('ألف مبارك للعروسين 🤍').waitFor();
await page.locator('.calendar summary').click();const download=page.waitForEvent('download');await page.getByRole('button',{name:'تقويم iPhone / تحميل ICS'}).click();assert.equal((await download).suggestedFilename(),'wedding.ics');
await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'test-results/hero-desktop.png'});
await page.goto('http://localhost:5173/admin/login');await page.getByLabel('اسم المستخدم').fill('test-admin');await page.getByLabel('كلمة المرور').fill('wrong');await page.getByRole('button',{name:'تسجيل الدخول',exact:true}).click();await page.getByRole('alert').waitFor();await page.getByLabel('كلمة المرور').fill('test-browser-password');await page.getByRole('button',{name:'تسجيل الدخول',exact:true}).click();await page.getByText('نظرة على فرحتكم').waitFor();await page.screenshot({path:'test-results/admin-desktop.png'});
await page.getByRole('button',{name:'تأكيدات الحضور',exact:true}).click();await page.getByRole('cell',{name:'سارة اختبار',exact:true}).first().waitFor();await page.getByLabel('البحث بالاسم أو رقم الهاتف').fill('no-match');await page.getByText('لا توجد نتائج مطابقة.').waitFor();await page.getByLabel('البحث بالاسم أو رقم الهاتف').fill('سارة');await page.getByRole('cell',{name:'سارة اختبار',exact:true}).first().waitFor();await page.getByLabel('تصفية الحضور').selectOption('declined');await page.getByText('لا توجد نتائج مطابقة.').waitFor();
await page.getByRole('button',{name:'رسائل الأحبة',exact:true}).click();await page.getByRole('button',{name:'إخفاء',exact:true}).click();await page.getByText('مخفية',{exact:true}).waitFor();await page.getByRole('button',{name:'إظهار',exact:true}).click();await page.getByRole('button',{name:'حذف',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'حذف',exact:true}).click();await page.getByText('لا توجد رسائل بعد.').waitFor();
await page.getByRole('button',{name:'إعدادات الدعوة',exact:true}).click();await page.getByLabel('اسم القاعة').fill('قاعة اختبار المتصفح');await page.getByRole('button',{name:'حفظ التغييرات'}).click();await page.getByRole('status').getByText('تم حفظ التغييرات').waitFor();
await page.getByRole('button',{name:'الموسيقى',exact:true}).click();await page.getByLabel('تغيير الأغنية').setInputFiles('public/music/wedding.mp3');await page.getByRole('button',{name:'رفع الأغنية',exact:true}).click();await page.getByRole('heading',{name:'wedding.mp3',exact:true}).waitFor();await page.getByRole('button',{name:'حذف / استعادة الأغنية الافتراضية'}).click();await page.getByRole('heading',{name:'بداية حكاية — لحن هادئ'}).waitFor();
await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'الرئيسية',exact:true}).click();await page.getByText('نظرة على فرحتكم').waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:'test-results/admin-mobile.png'});
await page.getByRole('button',{name:'تسجيل الخروج'}).click();await page.getByRole('heading',{name:'إدارة الدعوة'}).waitFor();await page.goto('http://localhost:5173/admin');await page.getByRole('heading',{name:'إدارة الدعوة'}).waitFor();assert.deepEqual(errors,[]);console.log('PASS: opening/audio/RSVP/guestbook/calendar/admin/search/filters/moderation/settings/music/logout; widths 375/390/393/402/430/1440; no JS errors.');await browser.close();
